name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        arch: ['amd64', 'arm64']
        pg: [17, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: install postgres and build dependencies
        run: |
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt install -y postgresql-${{ matrix.pg }} build-essential postgresql-server-dev-${{ matrix.pg }} libcurl4-openssl-dev uuid-dev --no-install-recommends

      - name: build pg_ivm
        run: |
          mkdir -p pg_ivm/.debpkg
          cd pg_ivm
          make USE_PGXS=1 DESTDIR=.debpkg install

      - name: build pg_clickhouse
        run: |
          mkdir -p pg_clickhouse/.debpkg
          cd pg_clickhouse
          make USE_PGXS=1 DESTDIR=.debpkg install

      - name: imv
        uses: jiro4989/build-deb-action@v4
        with:
          package: postgres-${{ matrix.pg }}-imv
          package_root: pg_imv/.debpkg
          maintainer: ClickHouse
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: ${{ matrix.arch }}
        id: build-imv

      - name: pg_clickhouse
        uses: jiro4989/build-deb-action@v4
        with:
          package: postgres-${{ matrix.pg }}-pg_clickhouse
          package_root: pg_clickhouse/.debpkg
          maintainer: ClickHouse
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: ${{ matrix.arch }}
        id: build-pg_clickhouse