name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        arch: ['amd64', 'arm64']
        pg: [16, 17, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: install postgres and build dependencies
        run: |
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt install -y postgresql-${{ matrix.pg }} build-essential postgresql-server-dev-${{ matrix.pg }} libcurl4-openssl-dev uuid-dev --no-install-recommends

      - name: build pg_ivm
        run: |
          mkdir -p pg_ivm/.debpkg
          cd pg_ivm
          make USE_PGXS=1 DESTDIR=.debpkg install

      - name: build pg_clickhouse
        run: |
          mkdir -p pg_clickhouse/.debpkg
          cd pg_clickhouse
          make USE_PGXS=1 DESTDIR=.debpkg install

      - name: package pg_ivm
        uses: jiro4989/build-deb-action@fa58571caeb53074d21ae3f1d128d0703e13b618
        with:
          package: postgres-${{ matrix.pg }}-pg-ivm
          package_root: pg_ivm/.debpkg
          maintainer: ClickHouse
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: ${{ matrix.arch }}
        id: build-pg_ivm

      - name: package pg_clickhouse
        uses: jiro4989/build-deb-action@fa58571caeb53074d21ae3f1d128d0703e13b618
        with:
          package: postgres-${{ matrix.pg }}-pg-clickhouse
          package_root: pg_clickhouse/.debpkg
          maintainer: ClickHouse
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: ${{ matrix.arch }}
        id: build-pg_clickhouse

      - name: Upload pg_ivm artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgresql-${{ matrix.pg }}-pg-ivm-${{ matrix.arch }}
          path: ${{ steps.build-pg_ivm.outputs.file_name }}

      - name: Upload pg_clickhouse artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgresql-${{ matrix.pg }}-pg-clickhouse-${{ matrix.arch }}
          path: ${{ steps.build-pg_clickhouse.outputs.file_name }}